added HW lesson_14
OdessaAlexSV/RobotDreams_AQA pull request #12
Opened 2022-05-31 18:10 UTC by OdessaAlexSV

2022-06-04 20:34 UTC, taraskarpenko requested changes

2022-06-04 20:34 UTC, taraskarpenko commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    void setHeadOfGroup(Student headOfGroup) {
А что если сюда передать null.
Получится группа без старосты

2022-06-04 20:34 UTC, taraskarpenko commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    public void addStudent(String id, Student student) {
ЗАчем сюда передавать id если студент его уже содержит.
А что если у студента ИД=5 а кто-то передаст сюда 2?

2022-06-04 20:34 UTC, taraskarpenko commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    public boolean removeStudent(String id) {
Хорошая идея возращать флаг успешности операции.

2022-06-04 20:34 UTC, taraskarpenko commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    public boolean renameStudent(String id, Student student) {
тут ИД в качестве параметра тоже лишний

2022-06-04 20:34 UTC, taraskarpenko commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    public void changeHeadOfGroup(Student newHeadOfGroup) {
Опять таки на вход можно передать null

2022-06-04 20:34 UTC, taraskarpenko commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +            students.replace(id, student);
тут replace лишний, так как вы уже изменили состояние обьекта ссылка на который находиться в листе.

2022-06-05 18:46 UTC, OdessaAlexSV commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    void setHeadOfGroup(Student headOfGroup) {
Добавил аннотацию "NonNull" из Lambok.
Проверку на NULL осуществляю в момент вызова функции.

2022-06-05 18:46 UTC, OdessaAlexSV commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    public void addStudent(String id, Student student) {
id - лишнее / удалил.
беру id из студента через getID

2022-06-05 18:46 UTC, OdessaAlexSV commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    public boolean renameStudent(String id, Student student) {
id - лишнее / удалил.
беру id из студента через getID

2022-06-05 18:46 UTC, OdessaAlexSV commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +    public void changeHeadOfGroup(Student newHeadOfGroup) {
Добавлена проверка на NULL внутри функции.

2022-06-05 18:46 UTC, OdessaAlexSV commented on lesson_14 [Incapsulation]/src/main/java/my/robotdreams/cc/hw/Group.java
> +            students.replace(id, student);
replace - удалён

2022-06-05 20:32 UTC, taraskarpenko approved these changes

2022-06-06 06:18 UTC, merged