added HW of lesson_16
OdessaAlexSV/RobotDreams_AQA pull request #13
Opened 2022-06-07 22:30 UTC by OdessaAlexSV

2022-06-10 21:54 UTC, taraskarpenko requested changes

2022-06-10 21:54 UTC, taraskarpenko commented on lesson_16 [Inheritance,Polymorphism]/src/main/java/my/robotdreams/cc/hw/Person.java
> +    private boolean partner;
А почему б не сделать private Person partner?
и соответственно всю логику женитьбы и развода ориентировать на то что б не только сменить фамилию, но и устанавливать партнера, да еще так что б если Маша стала женой Пети, то Петя тоже автоматически ставал мужем Маши, да еще перед этим проверять а не женат ли Петя на Кате

2022-06-11 21:49 UTC, OdessaAlexSV commented on lesson_16 [Inheritance,Polymorphism]/src/main/java/my/robotdreams/cc/hw/Person.java
> +    private boolean partner;
полностью согласен :)
--------------------------
1) заменён boolen partner на Person partner;
2) изменена логика женитьбы/развода 
при женитьбе - смена фамилии у супруги, для фамилии супруги - проверка на окончание (женский род), добавление партнера для обоих супругов, проверка что партнер не женат;
при разводе - возврат супруги к дев. фамилии, удаление партнера у обоих супругов.

2022-06-13 12:54 UTC, taraskarpenko commented on lesson_16 [Inheritance,Polymorphism]/src/main/java/my/robotdreams/cc/hw/Man.java
> +        }
Не очень понял логику этого if
Проверяем условие и не делаем ничего
По самому условию я так понял вы проверяете "А не женат ли этот персонаж на ком-то другом"
В таком случае имело б смысл сделать внутри return что б выполнение не пошло дальше, тоесть не регистрировать брак, но такой подход не очень, так как никак не сообщает об ошибке тому кто вызывал метод, логично было б выбрасывать какую-то ошибку, например UnsupportedOperationException, или даже сделать свою ошибку которая наследуется от этой.

И в целом, старайтесь избегать пустых if блоков, ну или добавляйте комментарий зачем он нужен

2022-06-13 14:03 UTC, merged

2022-06-13 14:05 UTC, taraskarpenko commented on lesson_16 [Inheritance,Polymorphism]/src/main/java/my/robotdreams/cc/hw/Man.java
> +        }
Если б до лекции по ошибкам в качестве результата вы выводили true/false это было б более чем достаточно
Это было скорее если уж будете исправлять то сделайте совсем красиво, так как исключения вы уже умеете использовать